# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "box1", primary: true do |box1|
    box1.vm.box = "box1"
    box1.vm.provision "shell" do |s|
      s.path = "shellprovision.sh"
      s.args = "box1"
    end
    box1.vm.box_url = "http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1709_01.VirtualBox.box"
    box1.vm.network "private_network", ip: "192.168.123.10", virtualbox__intnet: true, nic_type: "virtio"
    box1.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    box1.vm.network "forwarded_port", guest: 3389, host: 13389, protocol: "udp"
    box1.vm.network "forwarded_port", guest: 3389, host: 13389, protocol: "tcp"
    box1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.memory = 4096
      v.cpus = 4
    end
  end
# End of Vagrantfile
end
